# Generated by Django 3.1.6 on 2021-02-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.IntegerField()),
                ('floor', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.contact')),
                ('fk_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.address')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.people')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('specialty', models.ManyToManyField(to='people.Materials')),
            ],
            bases=('people.people',),
        ),
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.people')),
                ('course', models.CharField(max_length=50)),
                ('period', models.IntegerField()),
                ('class_course', models.CharField(max_length=5)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.classroom')),
            ],
            bases=('people.people',),
        ),
    ]
