# Generated by Django 3.1.6 on 2021-02-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='cpf_cnpj',
            new_name='cpf',
        ),
    ]
