# Generated by Django 3.1.6 on 2021-02-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210211_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='people',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='people.people'),
            preserve_default=False,
        ),
    ]
