# Generated by Django 3.1.6 on 2021-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20210211_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumn',
            name='class_room',
        ),
        migrations.AddField(
            model_name='alumn',
            name='class_room',
            field=models.ManyToManyField(to='people.ClassRoom'),
        ),
    ]
