# Generated by Django 3.1.6 on 2021-02-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20210211_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumn',
            name='class_course',
        ),
    ]
