# Generated by Django 3.1.6 on 2021-02-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_alumn_class_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='people',
        ),
        migrations.AddField(
            model_name='people',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='people.contact'),
            preserve_default=False,
        ),
    ]
